version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "agitprop_article_ner:1:1" # Replace with your desired topic name
    depends_on:
      - zookeeper
    networks:
      - kafka-net


  python-processor:
    build: ./language_processing  # Path to your Python service Dockerfile or source code
    depends_on:
      - surrealdb
      - kafka
    networks:
      - kafka-net

  surrealdb:
    image: surrealdb/surrealdb
    user: root
    command:  start file:mydatabase.db
    environment:
      - SURREAL_USER=root
      - SURREAL_PASS=root
      - SURREAL_LOG=trace
    ports:
      - 8000:8000    
    networks:
      - kafka-net

  # dotnet-webscraper:
  #   build: ./webscraper  # Path to your .NET web scraper Dockerfile or source code
  #   ports:
  #     - "8000:8000"  # Replace with the appropriate port for your .NET service
  #   networks:
  #     - kafka-net

  # orientdb:
  #   image: orientdb:latest
  #   container_name: orientdb
  #   ports:
  #     - "2480:2480"  # HTTP
  #     - "2424:2424"  # Binary
  #   environment:
  #     ORIENTDB_ROOT_PASSWORD: password  # Change 'your_password' to a secure password
  #   networks:
  #     - kafka-net

networks:
  kafka-net:
    driver: bridge
