version: '3.9'
services:
  python-processor:
    build: ./NER # Path to your Python service Dockerfile or source code
    depends_on:
      - surrealdb
    ports:
      - 5000:5000
    networks:
      - agitprop-net

  surrealdb:
    image: surrealdb/surrealdb
    user: root
    command:  start file:mydatabase.db
    environment:
      - SURREAL_USER=root
      - SURREAL_PASS=root
      - SURREAL_LOG=trace
    ports:
      - 8000:8000    
    networks:
      - agitprop-net
networks:
  agitprop-net:
    driver: bridge
