services:
  python-processor:
    image: ghcr.io/agitpropfigyelo/pythonnerservice:latest
    depends_on:
      - surrealdb
      - rabbitmq
    ports:
      - 5000:5000
    networks:
      - agitprop-net

  surrealdb:
    image: surrealdb/surrealdb:latest
    user: root
    command: start file:mydatabase.db
    environment:
      - SURREAL_USER=root
      - SURREAL_PASS=root
      - SURREAL_LOG=trace
    ports:
      - 8000:8000
    networks:
      - agitprop-net

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - agitprop-net

networks:
  agitprop-net:
    driver: bridge
