services:
  consumer:
    image: ghcr.io/agitpropfigyelo/agitprop-consumer:latest
    depends_on:
      - surrealdb
      - rabbitmq
    networks:
      - agitprop-net

  python-processor:
    image: ghcr.io/agitpropfigyelo/python-ner-service:latest
    ports:
      - 5000:5000
    networks:
      - agitprop-net

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000" # Expose the port to the host
    volumes:
      - ./mydata:/mydata # Persist data
    command: start --user root --pass root file:/mydata/mydatabase.db
    networks:
      - agitprop-net

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - agitprop-net

  rss-feed-reader:
    build:
      context: ./Agitprop.RssFeedReader
      dockerfile: Dockerfile
    depends_on:
      - surrealdb
      - rabbitmq
    networks:
      - agitprop-net

networks:
  agitprop-net:
    driver: bridge
