// <auto-generated />
using System;
using Agitprop.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agitprop.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agitprop.Infrastructure.Postgres.Models.PostgresArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Agitprop.Infrastructure.Postgres.Models.PostgresEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Agitprop.Infrastructure.Postgres.Models.PostgresMention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EntityId");

                    b.ToTable("mentions", (string)null);
                });

            modelBuilder.Entity("Agitprop.Infrastructure.Postgres.Models.PostgresMention", b =>
                {
                    b.HasOne("Agitprop.Infrastructure.Postgres.Models.PostgresArticle", "Article")
                        .WithMany("Mentions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agitprop.Infrastructure.Postgres.Models.PostgresEntity", "Entity")
                        .WithMany("Mentions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Agitprop.Infrastructure.Postgres.Models.PostgresArticle", b =>
                {
                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("Agitprop.Infrastructure.Postgres.Models.PostgresEntity", b =>
                {
                    b.Navigation("Mentions");
                });
#pragma warning restore 612, 618
        }
    }
}
