name: Release Container to GHCR

on:
  push:
    tags:
      - "v*" # Triggers on tags starting with 'v', e.g., v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU for multi-platform builds
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push container
      uses: docker/build-push-action@v4
      with:
        context: ./Agitprop.Consumer # Explicitly set the build context to the root folder
        file: ./Agitprop.Consumer/Dockerfile # Explicitly specify the Dockerfile in the root folder
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/agitprop-consumer:${{ github.ref_name }}
          ghcr.io/${{ github.repository_owner }}/agitprop-consumer:latest
